import type { LucideIcon } from "lucide-react";
import {
  Aperture,
  BadgeCheck,
  Blend,
  Box,
  BoxSelect,
  Cable,
  CircleDashed,
  CircleDot,
  CloudRain,
  Combine,
  Cpu,
  Crosshair,
  Cuboid,
  Download,
  Eye,
  FileSpreadsheet,
  FlipHorizontal2,
  GitBranch,
  Grid3x3,
  ImagePlus,
  ListTree,
  MemoryStick,
  Paintbrush,
  Pentagon,
  Ruler,
  Scale,
  Scan,
  Spline,
  Type,
  Workflow,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  Type,
  ImagePlus,
  Box,
  FileSpreadsheet,
  Scan,
  Spline,
  GitBranch,
  Eye,
  ListTree,
  BadgeCheck,
  Grid3x3,
  Circles: CircleDot,
  CircleDashed,
  Workflow,
  BoxSelect,
  FlipHorizontal2,
  Pentagon,
  Cuboid,
  Combine,
  Blend,
  Paintbrush,
  CloudRain,
  Ruler,
  Crosshair,
  Scale,
  Cpu,
  Download,
  Aperture,
  MemoryStick,
  Cable,
};

export function NodeIcon({ name, className }: { name: string; className?: string }) {
  const Icon = MAP[name] ?? Box;
  return <Icon className={className} strokeWidth={1.75} />;
}
