/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1BridgeRouteImport } from './routes/api/v1/bridge'
import { Route as ApiV1CatalogRouteImport } from './routes/api/v1/catalog'
import { Route as ApiV1CompileRouteImport } from './routes/api/v1/compile'
import { Route as ApiV1ExecuteRouteImport } from './routes/api/v1/execute'
import { Route as ApiV1GraphsRouteImport } from './routes/api/v1/graphs'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1OpenapiRouteImport } from './routes/api/v1/openapi'
import { Route as ApiV1GraphsIdRouteImport } from './routes/api/v1/graphs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BridgeRoute = ApiV1BridgeRouteImport.update({
  id: '/api/v1/bridge',
  path: '/api/v1/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CatalogRoute = ApiV1CatalogRouteImport.update({
  id: '/api/v1/catalog',
  path: '/api/v1/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CompileRoute = ApiV1CompileRouteImport.update({
  id: '/api/v1/compile',
  path: '/api/v1/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExecuteRoute = ApiV1ExecuteRouteImport.update({
  id: '/api/v1/execute',
  path: '/api/v1/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GraphsRoute = ApiV1GraphsRouteImport.update({
  id: '/api/v1/graphs',
  path: '/api/v1/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiRoute = ApiV1OpenapiRouteImport.update({
  id: '/api/v1/openapi',
  path: '/api/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GraphsIdRoute = ApiV1GraphsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1GraphsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/bridge': typeof ApiV1BridgeRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/compile': typeof ApiV1CompileRoute
  '/api/v1/execute': typeof ApiV1ExecuteRoute
  '/api/v1/graphs': typeof ApiV1GraphsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/graphs/$id': typeof ApiV1GraphsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/bridge': typeof ApiV1BridgeRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/compile': typeof ApiV1CompileRoute
  '/api/v1/execute': typeof ApiV1ExecuteRoute
  '/api/v1/graphs': typeof ApiV1GraphsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/graphs/$id': typeof ApiV1GraphsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/bridge': typeof ApiV1BridgeRoute
  '/api/v1/catalog': typeof ApiV1CatalogRoute
  '/api/v1/compile': typeof ApiV1CompileRoute
  '/api/v1/execute': typeof ApiV1ExecuteRoute
  '/api/v1/graphs': typeof ApiV1GraphsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/graphs/$id': typeof ApiV1GraphsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/bridge'
    | '/api/v1/catalog'
    | '/api/v1/compile'
    | '/api/v1/execute'
    | '/api/v1/graphs'
    | '/api/v1/health'
    | '/api/v1/openapi'
    | '/api/v1/graphs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/bridge'
    | '/api/v1/catalog'
    | '/api/v1/compile'
    | '/api/v1/execute'
    | '/api/v1/graphs'
    | '/api/v1/health'
    | '/api/v1/openapi'
    | '/api/v1/graphs/$id'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/bridge'
    | '/api/v1/catalog'
    | '/api/v1/compile'
    | '/api/v1/execute'
    | '/api/v1/graphs'
    | '/api/v1/health'
    | '/api/v1/openapi'
    | '/api/v1/graphs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1BridgeRoute: typeof ApiV1BridgeRoute
  ApiV1CatalogRoute: typeof ApiV1CatalogRoute
  ApiV1CompileRoute: typeof ApiV1CompileRoute
  ApiV1ExecuteRoute: typeof ApiV1ExecuteRoute
  ApiV1GraphsRoute: typeof ApiV1GraphsRouteWithChildren
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1OpenapiRoute: typeof ApiV1OpenapiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bridge': {
      id: '/api/v1/bridge'
      path: '/api/v1/bridge'
      fullPath: '/api/v1/bridge'
      preLoaderRoute: typeof ApiV1BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/catalog': {
      id: '/api/v1/catalog'
      path: '/api/v1/catalog'
      fullPath: '/api/v1/catalog'
      preLoaderRoute: typeof ApiV1CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/compile': {
      id: '/api/v1/compile'
      path: '/api/v1/compile'
      fullPath: '/api/v1/compile'
      preLoaderRoute: typeof ApiV1CompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/execute': {
      id: '/api/v1/execute'
      path: '/api/v1/execute'
      fullPath: '/api/v1/execute'
      preLoaderRoute: typeof ApiV1ExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/graphs': {
      id: '/api/v1/graphs'
      path: '/api/v1/graphs'
      fullPath: '/api/v1/graphs'
      preLoaderRoute: typeof ApiV1GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi': {
      id: '/api/v1/openapi'
      path: '/api/v1/openapi'
      fullPath: '/api/v1/openapi'
      preLoaderRoute: typeof ApiV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/graphs/$id': {
      id: '/api/v1/graphs/$id'
      path: '/$id'
      fullPath: '/api/v1/graphs/$id'
      preLoaderRoute: typeof ApiV1GraphsIdRouteImport
      parentRoute: typeof ApiV1GraphsRoute
    }
  }
}

interface ApiV1GraphsRouteChildren {
  ApiV1GraphsIdRoute: typeof ApiV1GraphsIdRoute
}

const ApiV1GraphsRouteChildren: ApiV1GraphsRouteChildren = {
  ApiV1GraphsIdRoute: ApiV1GraphsIdRoute,
}

const ApiV1GraphsRouteWithChildren = ApiV1GraphsRoute._addFileChildren(
  ApiV1GraphsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1BridgeRoute: ApiV1BridgeRoute,
  ApiV1CatalogRoute: ApiV1CatalogRoute,
  ApiV1CompileRoute: ApiV1CompileRoute,
  ApiV1ExecuteRoute: ApiV1ExecuteRoute,
  ApiV1GraphsRoute: ApiV1GraphsRouteWithChildren,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1OpenapiRoute: ApiV1OpenapiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
